---
version: 2
plugins:
    duplication:
        enabled: true
        config:
            languages:
                php:
                    mass_threshold: 50 # Default: 28
    editorconfig:
        enabled: true
    fixme:
        enabled: true
    phpcodesniffer:
        enabled: true
        config:
            standard: "PSR1,PSR2"
    phpmd:
        enabled: true
        config:
            file_extensions: "php"
            rulesets: "codesize.xml"
    sonar-php:
        enabled: true
        config:
            minimum_severity: minor # info, minor, major (default), critical, blocker
            tests_patterns:
                - tests/**
    git-legal:
        enabled: true
    markdownlint:
        enabled: true
    phan:
      enabled: false
      config:
        minimum-severity: 5
checks:
    argument-count:
        enabled: true
        config:
            threshold: 6
    complex-logic:
        enabled: true
        config:
            threshold: 4
    file-lines:
        enabled: true
        config:
            threshold: 250
    method-complexity:
        enabled: true
        config:
            threshold: 10
    method-count:
        enabled: true
        config:
            threshold: 30
    method-lines:
        enabled: true
        config:
            threshold: 40
    nested-control-flow:
        enabled: true
        config:
            threshold: 4
    return-statements:
        enabled: true
        config:
            threshold: 5
    similar-code:
        enabled: false
    identical-code:
        enabled: false
exclude_patterns:
    - "bin/"
    - "build/"
    - "config/"
    - "DoctrineMigrations/"
    - "heroku/"
    - "public/"
    - "templates/"
    - "tests/"
    - "translations/"
    - "var/"
    - "vendor/"
