language: php
sudo: false

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/.phpunit"
    - DATABASE_URL=pgsql://postgres@localhost:5432/api
    - CC_TEST_REPORTER_ID=0b9db21c5ccbad905dfd1f19508f07796b26d32803aeb1507663732ea09e6456
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

php:
  - '7.3'

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.phpunit

before_script:
  - psql -c 'create database api;' -U postgres
  - composer self-update
  - composer install
  - composer compile
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./bin/phpunit --testsuite=UnitSuite,IntegrationSuite
  - ./bin/console lint:yaml config --parse-tags
  - ./bin/console doctrine:schema:validate --no-interaction
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run --allow-risky=yes
  - ./bin/phpunit --coverage-clover ./build/logs/clover.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  - sonar-scanner

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: ezRW60w2Xd+tHocsikjzxHjXrBckcvm4qlf6Dqx5pJLUllN7BU13AHwzbmWU44zIzmNdJo/VgvQ4MvLsqN7/OFVPNpw+CJuvyEfPHU23advOwVfnsb6AGSCMFRBtsbowyNN9PtfFU6Cp4naJCDIkNiM4VpePDaCxUKQZm8bNbZoqZRzzZysYyJvcoXv6Vo9h1jGJCXSfrDQuxJpQinoSgLs/UYENsnRUrkDmbBjVjAFuEoWAfNVM0B1xcdL/pxbjyvZmc5YpPWuILuP3zWF+17SasGijKIL2uxeuN706OKdTtlZsrRcceV9ob7Er76AQWi5EmIFP2XjM+k4UBRhM7YZiG/JeksR/ndaXqHKld9+DZaS03zuWcFs69jjJIb6rCzlL+tuSZnUU1ly7NbdeZH1DALH2cpCU43PdnsOg5v5KwczYbTfIg2Uw+UHdO1+KGKxBp4vC6oHRCJN1xJ48CkHI8QAqjkL9x+HzHfESmnlFfM00NK2q36nXAz41mIPITmU4yiJFDTSAGDZbdfAdN0Berzxe6+nCNbJuMz3mSbvd5HDGnVhD1ltbrJpzeNg9Jo9+ieDFkvet8qN79+1kdP5lO4aKZFChApGWuUSBmN88KgzqKQUPir9ZZTwQ0DoceU3TAw+lCsVjvp2kZHvFDbxqXUwm4nGnGMI4+WZ6plI=
  app:
    master: shareps-app-production
    stage: shareps-app-stage
  on:
    repo: shareps/app

addons:
  sonarcloud:
    organization: shareps
    token:
      secure: LWyjeJH4bVtNEqOPGvbOVLyTxc89xMsw8oGg1lPkDQaZMRaBI+lQnoFF31b2EN7naaIDUwPqgsyz1YA8WcIv5KOGKx0111MFAM55hkOOJlGPzy3UEmPYjnjAVH2qGW0ihyGZFeLUV9MOhKFZqOmTheLpCBoVg7rNmOnMo2ipWw/qneGDNiqR8Wl3Lq+Q6jRNBk6KOmk0BSKyeaZprz8TX+s6hFr4I8s7SKm4rALlmIDdii2YzrbSQs4Uu4pFRuuVNTHoWM0VtAIM1WctFuPTBjCRYKpdCy9By1Zn4ujwoMzpRaDrphVmOet3NpsSB17QWM1246XT1TGvuh/aPo0OVs0chNY6Hu4JHOFcST9hUFcqXWcwxqjMQkinn9lEmUGKzsvSyocUEC/cfoaPBRGRbEsTAft7WoVieVeRq660Wg4lR2LLtgxDpF5nFeky9WY8mAXeC2L2OtFveU6Mu/4Vn4PbW1fLiOmI9fr/iu4dc5jTfH21y6qU3GVK1QoecB+g9G7QNHmcgAvS9CmEcC6a5Z+ugSVEIL6cSKO4KDKw6co4MGnvpMlqK7VVZG07cqzlCfLz9WZ9rlb3tQzElLoDSfCd9cauaZ6km7d2hf38xENzvsRd1vADItZoSs4iqwbdYpt1edzOVOE7VWyvHxt3OKOMCMABiQnzWNhWAtfyUus=
