language: php
sudo: false

services:
    - postgresql

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR="$HOME/.phpunit"
        - DATABASE_URL=pgsql://postgres@localhost:5432/api

php:
    - '7.3'

before_script:
    - psql -c 'create database api;' -U postgres
    - composer self-update
    - composer install

script:
    - ./bin/phpunit
    - ./bin/console lint:yaml config --parse-tags
    - ./bin/console lint:twig templates --env=prod
    - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
    - ./vendor/bin/php-cs-fixer fix --diff --dry-run --allow-risky=yes -v
#    - ./bin/phpunit --coverage-clover ./var/build/phpunit-coverage-clover.xml

notifications:
    email: false
