version: '3.4'

x-cache:
  &cache
  cache_from:
    - quay.io/api-platform/php
    - quay.io/api-platform/nginx

services:
  db:
    # In production, you may want to use a managed database service
    image: postgres:10-alpine
    container_name: sharep_db
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-platform
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  php:
    image: quay.io/api-platform/php
    container_name: sharep_php
    build:
      context: ""
      target: sharep_php
      <<: *cache
    depends_on:
      - db
    # Comment out these volumes in production
    volumes:
      - ./:/srv/sharep:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      - ./var:/srv/sharep/var:rw
    ports:
      - 9111:9111

  api:
    image: quay.io/api-platform/nginx
    container_name: sharep_nginx
    build:
      context: ""
      target: sharep_nginx
      <<: *cache
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./public:/srv/sharep/public:ro
    ports:
      - 8080:80

  h2-proxy:
    # Don't use this proxy in prod
    container_name: sharep_proxy
    build:
      context: docker/h2-proxy
    depends_on:
      - api
    ports:
      - 8443:8443

volumes:
  db-data: {}
